### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by iJaySin** [BrendonCurmi/FusionPixelmon#6]
- When I try to buy 2 or more levels at a time, it only gives me 1 level.
- Decreasing multiple levels at a time works.
- Buying/decreasing multiple EVs & IVs at a time works.
- Pokemon's form reverts back into original form after a battle or when you throw it out and return it (Don't know if this was intended).

Sponge: 7.2.0
Forge: 2838
Pixelmon: 7.2.2

**Comment by BrendonCurmi** [comment]
Hey :)

1. That's strange. When buying levels, it should close your inventory and give you levels the same way you'd earn them by defeating a wild pokemon or trainer. Testing this, it works for me and I get all the levels
2. Decreasing multiple levels at a time is intended
3. Buying/decreasing multiple EVs & IVs at a time is intended. I coded the backend logic in a way to be able to handle all of it all at once
4. Form and Evolution are mostly aesthetic features due to the volatile nature of how quickly they can change. Ex: by changing held item, returning to pokeball, etc. But for me, I'm able to change form and throw/return and battle, without the form reverting back

SpongeForge: 2825-7.1.6
Forge: 2847
Pixelmon: 7.0.8, 7.1.1, & 7.2.2

Tried to test with SpongeForge 2838-7.2.0 but my antivirus blocks me from downloading it. Maybe try updating your Forge and downgrading Sponge?

**Comment by iJaySin** [comment]
Thanks for replying.
So multiple levels works when I downgraded sponge to 7.1.6 and upgraded forge to 2847. 
When I tried to keep forge at 2847 and change sponge back to 7.2.0, the same problem persists. 
So it seems like the problem lies on sponge 7.2.0. Thanks for the help!
